"""
Module for handling postcode data from UK sources.

This module provides functions to:
1. Load National Statistics Postcode Lookup (NSPL) data

Note: Before using this module, you must first run download_nspl.py to download
the postcode data and save it as data/nspl.parquet.
"""

import polars as pl
from pathlib import Path


def get_postcode_data(
    nspl_path: str = "data/nspl.parquet",
) -> pl.DataFrame:
    """
    Loads the National Statistics Postcode Lookup (NSPL) data from a parquet file.

    The parquet file should be generated by running download_nspl.py first.

    Args:
        nspl_path: Path to the NSPL parquet file. Defaults to data/nspl.parquet.

    Returns:
        A Polars DataFrame containing postcode (pcd) and local authority (laua) columns.
        Postcodes are normalized (spaces removed).

    Raises:
        FileNotFoundError: If the parquet file doesn't exist.
            Run download_nspl.py first to generate the file.
    """
    parquet_file = Path(nspl_path)

    if not parquet_file.exists():
        raise FileNotFoundError(
            f"NSPL data file not found at {nspl_path}. "
            "Please run 'uv run src/finding_data/download_nspl.py' first to download the data."
        )

    print(f"Loading NSPL postcode data from {nspl_path}...")
    postcodes_full = pl.read_parquet(nspl_path)
    print(f"Loaded {len(postcodes_full):,} postcodes.")

    return postcodes_full


