"""
Module for handling postcode and population data from UK sources.

This module provides functions to:
1. Load National Statistics Postcode Lookup (NSPL) data
2. Download and combine population data from England, Wales, Scotland, and Northern Ireland
3. Merge postcode geographic data with population data

Note: Before using this module, you must first run download_nspl.py to download
the postcode data and save it as data/nspl.parquet.
"""

import polars as pl
import httpx
from pathlib import Path


def get_postcode_data(
    nspl_path: str = "data/nspl.parquet",
) -> pl.DataFrame:
    """
    Loads the National Statistics Postcode Lookup (NSPL) data from a parquet file.

    The parquet file should be generated by running download_nspl.py first.

    Args:
        nspl_path: Path to the NSPL parquet file. Defaults to data/nspl.parquet.

    Returns:
        A Polars DataFrame containing postcode (pcd) and local authority (laua) columns.
        Postcodes are normalized (spaces removed).

    Raises:
        FileNotFoundError: If the parquet file doesn't exist.
            Run download_nspl.py first to generate the file.
    """
    parquet_file = Path(nspl_path)

    if not parquet_file.exists():
        raise FileNotFoundError(
            f"NSPL data file not found at {nspl_path}. "
            "Please run 'uv run src/finding_data/download_nspl.py' first to download the data."
        )

    print(f"Loading NSPL postcode data from {nspl_path}...")
    postcodes_full = pl.read_parquet(nspl_path)
    print(f"Loaded {len(postcodes_full):,} postcodes.")

    return postcodes_full


def get_pop_data(
    eng_wales_postcode_pop_url: str = "https://www.nomisweb.co.uk/output/census/2021/pcd_p002.csv",
    scotland_postcode_pop_url: str = "https://www.nrscotland.gov.uk/media/mafbfvmj/postcode2022_usualresidentpopulation.csv",
    ni_postcode_pop_url: str = "https://www.nisra.gov.uk/system/files/statistics/census-2021-person-and-household-estimates-for-postcodes-in-northern-ireland.xlsx",
) -> pl.DataFrame:
    """
    Downloads and combines population data for all UK postcodes.

    Fetches postcode-level population data from:
    - England and Wales (NOMIS)
    - Scotland (National Records of Scotland)
    - Northern Ireland (NISRA)

    Uses httpx for consistent, modern HTTP handling.

    Args:
        eng_wales_postcode_pop_url: URL for England and Wales postcode population data.
        scotland_postcode_pop_url: URL for Scotland postcode population data.
        ni_postcode_pop_url: URL for Northern Ireland postcode population data.

    Returns:
        A Polars DataFrame with columns:
            - postcode: Original postcode format
            - population: Number of usual residents
            - pcd: Normalized postcode (spaces removed)

    Raises:
        httpx.HTTPError: If any of the downloads fail.
    """
    print("Downloading population data for Scotland...")
    with httpx.stream(
        "GET", scotland_postcode_pop_url, follow_redirects=True
    ) as response:
        response.raise_for_status()
        scotland_content = response.read()

    scotland_postcode_pop = pl.read_csv(scotland_content).select(
        pl.col("Postcode").cast(pl.String).alias("postcode"),
        pl.col("UsualResidentPopulation")
        .cast(pl.Int64, strict=False)
        .alias("population"),
    )

    print("Downloading population data for England and Wales...")
    eng_wales_pop = pl.read_csv(eng_wales_postcode_pop_url).select(
        pl.col("Postcode").cast(pl.String).alias("postcode"),
        pl.col("Count").cast(pl.Int64, strict=False).alias("population"),
    )

    print("Downloading population data for Northern Ireland...")
    ni_postcode_pop = (
        pl.read_excel(
            ni_postcode_pop_url,
            sheet_name="Postcode",
            columns=[0, 4],
            has_header=False,
        )
        .slice(6)
        .select(
            pl.col("column_1").cast(pl.String).alias("postcode"),
            pl.col("column_2").cast(pl.Int64, strict=False).alias("population"),
        )
    )

    combined_df = (
        pl.concat(
            [
                scotland_postcode_pop,
                eng_wales_pop,
                ni_postcode_pop,
            ]
        )
        .drop_nulls()
        .with_columns(pl.col("postcode").str.replace_all(" ", "").alias("pcd"))
    )

    return combined_df


def get_populous_postcodes() -> pl.DataFrame:
    """
    Combines postcode geographic data with population data.

    Returns:
        A Polars DataFrame containing postcodes with their local authority codes
        and population data.
    """
    postcode_df = get_postcode_data()
    postcode_pop = get_pop_data()

    postcode_merge = postcode_df.join(
        postcode_pop, how="inner", left_on="pcd", right_on="pcd"
    ).drop("pcd")

    return postcode_merge
